%YAML 1.1
---
$schema: asdf://stsci.edu/datamodels/roman/schemas/rad_schema-1.0.0
id: asdf://stsci.edu/datamodels/roman/schemas/CGI/keywords/cgi_mechanism_named_settings-1.0.0

title: Meckanism named setting information
