%YAML 1.1
---
$schema: asdf://stsci.edu/datamodels/roman/schemas/rad_schema-1.0.0
id: asdf://stsci.edu/datamodels/roman/schemas/CGI/keywords/cgi_mechanism_named_settings-1.0.0

title: Meckanism named setting information
extName: SSC

type: object
properties:
  SPAMNAME:
    title: Closest Shaped Pupil Alignment Mechanism named setting
    description: Placeholder
    type: string
    maxLength: 128
    archive_catalog:
      datatype: nvarchar(128)
      destination: [CGIPlaceholder.placeholder]
  FPAMNAME:
    title: Closest Focal Plane Alignment Mechanism named setting
    description: Placeholder
    type: string
    maxLength: 128
    archive_catalog:
      datatype: nvarchar(128)
      destination: [CGIPlaceholder.placeholder]
  LSAMNAME:
    title: Closest Lyot Stop Alignment Mechanism named setting
    description: Placeholder
    type: string
    maxLength: 128
    archive_catalog:
      datatype: nvarchar(128)
      destination: [CGIPlaceholder.placeholder]
  FSAMNAME:
    title: Closest Field Stop Alignment Mechanism named setting
    description: Placeholder
    type: string
    maxLength: 128
    archive_catalog:
      datatype: nvarchar(128)
      destination: [CGIPlaceholder.placeholder]
  CFAMNAME:
    title: Closest Color Filter Alignment Mechanism named setting
    description: Placeholder
    type: string
    maxLength: 128
    archive_catalog:
      datatype: nvarchar(128)
      destination: [CGIPlaceholder.placeholder]
  DPAMNAME:
    title: Closest Dispersion Polarizer Alignment Mechanism named setting
    description: Placeholder
    type: string
    maxLength: 128
    archive_catalog:
      datatype: nvarchar(128)
      destination: [CGIPlaceholder.placeholder]

required: [SPAMNAME, FPAMNAME, LSAMNAME, FSAMNAME, CFAMNAME, DPAMNAME]
