%YAML 1.1
---
$schema: asdf://stsci.edu/datamodels/roman/schemas/rad_schema-1.0.0
id: asdf://stsci.edu/datamodels/roman/schemas/SSC/CGI/keywords/cgi_mechanism_named_settings-1.0.0

title: Mechanism named setting information
extName: SSC

type: object
properties:
  SPAMNAME:
    title: Closest Shaped Pupil Alignment Mechanism named setting
    description: Closest shaped pupil alignment mechanism setting
    type: string
    maxLength: 128
    archive_catalog:
      datatype: nvarchar(128)
      destination: [CGIPlaceholder.spamname]
  FPAMNAME:
    title: Closest Focal Plane Alignment Mechanism named setting
    description: Closest focal plan alignment mechanism setting
    type: string
    maxLength: 128
    archive_catalog:
      datatype: nvarchar(128)
      destination: [CGIPlaceholder.fpamname]
  LSAMNAME:
    title: Closest Lyot Stop Alignment Mechanism named setting
    description: Closest Lyot stop alignment mechanism setting
    type: string
    maxLength: 128
    archive_catalog:
      datatype: nvarchar(128)
      destination: [CGIPlaceholder.lsamname]
  FSAMNAME:
    title: Closest Field Stop Alignment Mechanism named setting
    description: Closest field stop alignment mechanism setting
    type: string
    maxLength: 128
    archive_catalog:
      datatype: nvarchar(128)
      destination: [CGIPlaceholder.fsamname]
  CFAMNAME:
    title: Closest Color Filter Alignment Mechanism named setting
    description: Closest filter alignment mechanism setting
    type: string
    maxLength: 128
    archive_catalog:
      datatype: nvarchar(128)
      destination: [CGIPlaceholder.cfamname]
  DPAMNAME:
    title: Closest Dispersion Polarizer Alignment Mechanism named setting
    description: Closest dispersion polarizer alignment mechanism setting
    type: string
    maxLength: 128
    archive_catalog:
      datatype: nvarchar(128)
      destination: [CGIPlaceholder.dpamname]

required: [SPAMNAME, FPAMNAME, LSAMNAME, FSAMNAME, CFAMNAME, DPAMNAME]
