name: CI

on:
  push:
    branches:
      - main
      - "*"
    tags:
      - '*'
  pull_request:
  schedule:
    # Weekly Monday 9AM build
    - cron: '0 9 * * 1'

jobs:
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@8c0fde6f7e926df6ed7057255d29afa9c1ad5320  # v1.16.0
    with:
      envs: |
        - linux: py311-xdist
        - linux: py312-xdist-cov
          coverage: codecov
        - linux: py313-xdist

  roman_datamodels:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@8c0fde6f7e926df6ed7057255d29afa9c1ad5320  # v1.16.0
    with:
      envs: |
        - linux: roman_datamodels-xdist
